// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmOCF7vAICTaEbZucbsT2YzSqL9xzOsDs',
    appId: '1:278573889802:web:45b6740ac2a18f9d7ae2f3',
    messagingSenderId: '278573889802',
    projectId: 'school-18856',
    authDomain: 'school-18856.firebaseapp.com',
    storageBucket: 'school-18856.firebasestorage.app',
    measurementId: 'G-Q31RL51KHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxcPwcsUZShaDsmaO-3zHnvB7BDYZaP-4',
    appId: '1:278573889802:android:d9c21035312e6a177ae2f3',
    messagingSenderId: '278573889802',
    projectId: 'school-18856',
    storageBucket: 'school-18856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtp-UHW9mlT0b4StOOAMaAyPtHEn3R4k',
    appId: '1:278573889802:ios:fe61c728bb14e98d7ae2f3',
    messagingSenderId: '278573889802',
    projectId: 'school-18856',
    storageBucket: 'school-18856.firebasestorage.app',
    iosClientId: '278573889802-it93bpsh1ifte76cg643i12kuja8ck71.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmOCF7vAICTaEbZucbsT2YzSqL9xzOsDs',
    appId: '1:278573889802:web:c489d7f27af8bd8b7ae2f3',
    messagingSenderId: '278573889802',
    projectId: 'school-18856',
    authDomain: 'school-18856.firebaseapp.com',
    storageBucket: 'school-18856.firebasestorage.app',
    measurementId: 'G-X8114S39JR',
  );

}